import os
import shutil
from pathlib import Path

def create_directory(path):
    if not os.path.exists(path):
        os.makedirs(path)

def create_file(file_path):
    if not os.path.exists(file_path):
        with open(file_path, 'w'):
            pass

def create_bug_bounty_structure(base_path):
    bug_bounty_path = os.path.join(base_path, "Bug Bounty")
    create_directory(bug_bounty_path)
    create_file(os.path.join(bug_bounty_path, "01_Introduction.md"))
    create_directory(os.path.join(bug_bounty_path, "02_Getting Started"))
    create_file(os.path.join(bug_bounty_path, "02_Getting Started", "01_Creating Bug Bounty Accounts.md"))
    create_file(os.path.join(bug_bounty_path, "02_Getting Started", "02_Understanding Bug Bounty Platforms.md"))
    create_file(os.path.join(bug_bounty_path, "02_Getting Started", "03_Profile Setup and Verification.md"))
    create_directory(os.path.join(bug_bounty_path, "03_Methodologies and Processes"))
    create_directory(os.path.join(bug_bounty_path, "03_Methodologies and Processes", "01_Reconnaissance Techniques"))
    create_file(os.path.join(bug_bounty_path, "03_Methodologies and Processes", "01_Reconnaissance Techniques", "01_Passive and Active Recon.md"))
    create_file(os.path.join(bug_bounty_path, "03_Methodologies and Processes", "01_Reconnaissance Techniques", "02_Information Gathering Tools.md"))
    create_directory(os.path.join(bug_bounty_path, "03_Methodologies and Processes", "02_Vulnerability Discovery"))
    create_file(os.path.join(bug_bounty_path, "03_Methodologies and Processes", "02_Vulnerability Discovery", "01_Automated Scanning.md"))
    create_file(os.path.join(bug_bounty_path, "03_Methodologies and Processes", "02_Vulnerability Discovery", "02_Manual Testing.md"))
    create_directory(os.path.join(bug_bounty_path, "03_Methodologies and Processes", "03_Exploitation"))
    create_file(os.path.join(bug_bounty_path, "03_Methodologies and Processes", "03_Exploitation", "01_Techniques for Proving Impact.md"))
    create_file(os.path.join(bug_bounty_path, "03_Methodologies and Processes", "03_Exploitation", "02_Exploitation Tools.md"))
    create_directory(os.path.join(bug_bounty_path, "03_Methodologies and Processes", "04_Post-Exploitation"))
    create_file(os.path.join(bug_bounty_path, "03_Methodologies and Processes", "04_Post-Exploitation", "01_Data Exfiltration.md"))
    create_file(os.path.join(bug_bounty_path, "03_Methodologies and Processes", "04_Post-Exploitation", "02_Pivoting.md"))
    create_file(os.path.join(bug_bounty_path, "03_Methodologies and Processes", "04_Post-Exploitation", "03_Privilege Escalation.md"))
    create_directory(os.path.join(bug_bounty_path, "03_Methodologies and Processes", "05_Reporting and Collaboration"))
    create_file(os.path.join(bug_bounty_path, "03_Methodologies and Processes", "05_Reporting and Collaboration", "01_Crafting Effective Reports.md"))
    create_file(os.path.join(bug_bounty_path, "03_Methodologies and Processes", "05_Reporting and Collaboration", "02_Collaborating with Program Owners.md"))
    create_directory(os.path.join(bug_bounty_path, "04_Strategies and Tips"))
    create_file(os.path.join(bug_bounty_path, "04_Strategies and Tips", "01_Goal-Oriented Testing.md"))
    create_file(os.path.join(bug_bounty_path, "04_Strategies and Tips", "02_Target Selection.md"))
    create_file(os.path.join(bug_bounty_path, "04_Strategies and Tips", "03_Time Management.md"))
    create_file(os.path.join(bug_bounty_path, "04_Strategies and Tips", "04_Continuous Learning.md"))
    create_file(os.path.join(bug_bounty_path, "04_Strategies and Tips", "05_Bug Bounty Etiquette.md"))
    create_directory(os.path.join(bug_bounty_path, "05_Tools"))
    create_directory(os.path.join(bug_bounty_path, "05_Tools", "01_Reconnaissance Tools"))
    create_file(os.path.join(bug_bounty_path, "05_Tools", "01_Reconnaissance Tools", "01_Subdomain Enumeration.md"))
    create_file(os.path.join(bug_bounty_path, "05_Tools", "01_Reconnaissance Tools", "02_WHOIS Lookup.md"))
    create_file(os.path.join(bug_bounty_path, "05_Tools", "01_Reconnaissance Tools", "03_DNS Analysis.md"))
    create_directory(os.path.join(bug_bounty_path, "05_Tools", "02_Vulnerability Scanning Tools"))
    create_file(os.path.join(bug_bounty_path, "05_Tools", "02_Vulnerability Scanning Tools", "01_Automated Scanners (e.g., Nikto, Nmap).md"))
    create_file(os.path.join(bug_bounty_path, "05_Tools", "02_Vulnerability Scanning Tools", "02_Manual Testing Tools (e.g., Burp Suite, OWASP ZAP).md"))
    create_directory(os.path.join(bug_bounty_path, "05_Tools", "03_Exploitation Tools"))
    create_file(os.path.join(bug_bounty_path, "05_Tools", "03_Exploitation Tools", "01_Metasploit.md"))
    create_file(os.path.join(bug_bounty_path, "05_Tools", "03_Exploitation Tools", "02_ExploitDB.md"))
    create_file(os.path.join(bug_bounty_path, "05_Tools", "03_Exploitation Tools", "03_Buffer Overflow Tools.md"))
    create_directory(os.path.join(bug_bounty_path, "05_Tools", "04_Post-Exploitation Tools"))
    create_file(os.path.join(bug_bounty_path, "05_Tools", "04_Post-Exploitation Tools", "01_Data Exfiltration Tools.md"))
    create_file(os.path.join(bug_bounty_path, "05_Tools", "04_Post-Exploitation Tools", "02_Privilege Escalation Scripts.md"))
    create_file(os.path.join(bug_bounty_path, "05_Tools", "04_Post-Exploitation Tools", "03_Pivoting Utilities.md"))
    create_directory(os.path.join(bug_bounty_path, "05_Tools", "05_Reporting Tools"))
    create_file(os.path.join(bug_bounty_path, "05_Tools", "05_Reporting Tools", "01_Bug Bounty Platforms.md"))
    create_file(os.path.join(bug_bounty_path, "05_Tools", "05_Reporting Tools", "02_Collaborative Platforms (e.g., HackerOne, Bugcrowd).md"))
    create_file(os.path.join(bug_bounty_path, "05_Tools", "05_Reporting Tools", "03_Version Control Systems (e.g., Git).md"))
    create_directory(os.path.join(bug_bounty_path, "06_Learning Resources"))
    create_directory(os.path.join(bug_bounty_path, "06_Learning Resources", "01_Books"))
    create_file(os.path.join(bug_bounty_path, "06_Learning Resources", "01_Books", "01_Essential Bug Bounty Reading.md"))
    create_file(os.path.join(bug_bounty_path, "06_Learning Resources", "01_Books", "02_Web Application Security Books.md"))
    create_directory(os.path.join(bug_bounty_path, "06_Learning Resources", "02_Courses"))
    create_file(os.path.join(bug_bounty_path, "06_Learning Resources", "02_Courses", "01_Online Platforms Offering Bug Bounty Courses.md"))
    create_file(os.path.join(bug_bounty_path, "06_Learning Resources", "02_Courses", "02_Certifications to Boost Bug Bounty Skills.md"))
    create_directory(os.path.join(bug_bounty_path, "06_Learning Resources", "03_Websites and Forums"))
    create_file(os.path.join(bug_bounty_path, "06_Learning Resources", "03_Websites and Forums", "01_Active Bug Bounty Communities.md"))
    create_file(os.path.join(bug_bounty_path, "06_Learning Resources", "03_Websites and Forums", "02_Platforms for Information Sharing.md"))
    create_directory(os.path.join(bug_bounty_path, "06_Learning Resources", "04_Blogs and Write-ups"))
    create_file(os.path.join(bug_bounty_path, "06_Learning Resources", "04_Blogs and Write-ups", "01_Learning from Real-world Examples.md"))
    create_file(os.path.join(bug_bounty_path, "06_Learning Resources", "04_Blogs and Write-ups", "02_Following Successful Bug Hunters.md"))
    create_directory(os.path.join(bug_bounty_path, "07_Challenges and Labs"))
    create_directory(os.path.join(bug_bounty_path, "07_Challenges and Labs", "01_CTF Platforms"))
    create_file(os.path.join(bug_bounty_path, "07_Challenges and Labs", "01_CTF Platforms", "01_Practicing with Capture The Flag Challenges.md"))
    create_file(os.path.join(bug_bounty_path, "07_Challenges and Labs", "01_CTF Platforms", "02_CTF Write-ups and Analysis.md"))
    create_directory(os.path.join(bug_bounty_path, "07_Challenges and Labs", "02_Bug Bounty Platforms with Labs"))
    create_file(os.path.join(bug_bounty_path, "07_Challenges and Labs", "02_Bug Bounty Platforms with Labs", "01_Hands-on Practice with Simulated Environments.md"))
    create_file(os.path.join(bug_bounty_path, "07_Challenges and Labs", "02_Bug Bounty Platforms with Labs", "02_Leveraging Lab Environments for Skill Development.md"))
    create_directory(os.path.join(bug_bounty_path, "08_Bug Bounty in Practice"))
    create_directory(os.path.join(bug_bounty_path, "08_Bug Bounty in Practice", "01_Case Studies"))
    create_file(os.path.join(bug_bounty_path, "08_Bug Bounty in Practice", "01_Case Studies", "01_Notable Bug Bounty Success Stories.md"))
    create_file(os.path.join(bug_bounty_path, "08_Bug Bounty in Practice", "01_Case Studies", "02_Lessons Learned from Public Disclosures.md"))
    create_directory(os.path.join(bug_bounty_path, "08_Bug Bounty in Practice", "02_Interviews with Bug Hunters"))
    create_file(os.path.join(bug_bounty_path, "08_Bug Bounty in Practice", "02_Interviews with Bug Hunters", "01_Insights from Experienced Bug Bounty Hunters.md"))
    create_file(os.path.join(bug_bounty_path, "08_Bug Bounty in Practice", "02_Interviews with Bug Hunters", "02_Tips for Aspiring Bug Hunters.md"))


def create_certification_structure(base_path):
    certification_path = os.path.join(base_path, "Certification")
    create_directory(certification_path)
    create_file(os.path.join(certification_path, "01_Overview.md"))
    create_directory(os.path.join(certification_path, "02_Getting Started"))
    create_file(os.path.join(certification_path, "02_Getting Started", "01_Choosing the Right Certification.md"))
    create_file(os.path.join(certification_path, "02_Getting Started", "02_Prerequisites and Requirements.md"))
    create_file(os.path.join(certification_path, "02_Getting Started", "03_Exam Preparation Strategies.md"))
    create_directory(os.path.join(certification_path, "03_Popular Certifications"))
    create_file(os.path.join(certification_path, "03_Popular Certifications", "01_CEH (Certified Ethical Hacker).md"))
    create_file(os.path.join(certification_path, "03_Popular Certifications", "02_CISSP (Certified Information Systems Security Professional).md"))
    create_file(os.path.join(certification_path, "03_Popular Certifications", "03_CompTIA Security+.md"))
    create_file(os.path.join(certification_path, "03_Popular Certifications", "04_OSCP (Offensive Security Certified Professional).md"))
    create_file(os.path.join(certification_path, "03_Popular Certifications", "05_OSWE (Offensive Security Web Expert).md"))
    create_file(os.path.join(certification_path, "03_Popular Certifications", "06_OSCE (Offensive Security Certified Expert).md"))
    create_directory(os.path.join(certification_path, "04_Certification Tracks"))
    create_file(os.path.join(certification_path, "04_Certification Tracks", "01_Ethical Hacking and Penetration Testing.md"))
    create_file(os.path.join(certification_path, "04_Certification Tracks", "02_Network Security.md"))
    create_file(os.path.join(certification_path, "04_Certification Tracks", "03_Cloud Security.md"))
    create_file(os.path.join(certification_path, "04_Certification Tracks", "04_Web Application Security.md"))
    create_file(os.path.join(certification_path, "04_Certification Tracks", "05_Incident Response and Forensics.md"))
    create_directory(os.path.join(certification_path, "05_Study Resources"))
    create_file(os.path.join(certification_path, "05_Study Resources", "01_Books and Study Guides.md"))
    create_file(os.path.join(certification_path, "05_Study Resources", "02_Online Courses and Training.md"))
    create_file(os.path.join(certification_path, "05_Study Resources", "03_Practice Exams and Labs.md"))
    create_file(os.path.join(certification_path, "05_Study Resources", "04_Study Groups and Communities.md"))
    create_directory(os.path.join(certification_path, "06_Exam Day Tips"))
    create_file(os.path.join(certification_path, "06_Exam Day Tips", "01_Preparing for Exam Day.md"))
    create_file(os.path.join(certification_path, "06_Exam Day Tips", "02_During the Exam.md"))
    create_file(os.path.join(certification_path, "06_Exam Day Tips", "03_Post-Exam Activities.md"))
    create_directory(os.path.join(certification_path, "07_Maintaining and Renewing Certifications"))
    create_file(os.path.join(certification_path, "07_Maintaining and Renewing Certifications", "01_Continuing Education Requirements.md"))
    create_file(os.path.join(certification_path, "07_Maintaining and Renewing Certifications", "02_Renewal Processes.md"))
    create_file(os.path.join(certification_path, "07_Maintaining and Renewing Certifications", "03_Staying Updated with Industry Changes.md"))
    create_directory(os.path.join(certification_path, "08_Certification Success Stories"))
    create_file(os.path.join(certification_path, "08_Certification Success Stories", "01_Personal Experiences.md"))
    create_file(os.path.join(certification_path, "08_Certification Success Stories", "02_Lessons Learned.md"))
    create_file(os.path.join(certification_path, "08_Certification Success Stories", "03_Advice from Certified Professionals.md"))
    create_directory(os.path.join(certification_path, "09_Related Certifications"))
    create_file(os.path.join(certification_path, "09_Related Certifications", "01_Vendor-Specific Certifications (e.g., Cisco, Microsoft).md"))
    create_file(os.path.join(certification_path, "09_Related Certifications", "02_Specialized Certifications (e.g., CISSP, CISM).md"))
    create_file(os.path.join(certification_path, "09_Related Certifications", "03_Industry-Recognized Certifications.md"))
    create_directory(os.path.join(certification_path, "10_Certification and Career Paths"))
    create_file(os.path.join(certification_path, "10_Certification and Career Paths", "01_Planning Your Career Path.md"))
    create_file(os.path.join(certification_path, "10_Certification and Career Paths", "02_Advancing Your Career with Certifications.md"))
    create_directory(os.path.join(certification_path, "11_Certifications in Demand"))
    create_file(os.path.join(certification_path, "11_Certifications in Demand", "01_Emerging Certifications.md"))
    create_file(os.path.join(certification_path, "11_Certifications in Demand", "02_Industry Trends and Predictions.md"))
    create_directory(os.path.join(certification_path, "12_Tips for Successful Certification Journey"))
    create_file(os.path.join(certification_path, "12_Tips for Successful Certification Journey", "01_Time Management.md"))
    create_file(os.path.join(certification_path, "12_Tips for Successful Certification Journey", "02_Balancing Work and Study.md"))
    create_file(os.path.join(certification_path, "12_Tips for Successful Certification Journey", "03_Building a Strong Study Routine.md"))
    create_file(os.path.join(certification_path, "12_Tips for Successful Certification Journey", "04_Dealing with Exam Anxiety.md"))
    create_directory(os.path.join(certification_path, "13_Certification Resources and Tools"))
    create_file(os.path.join(certification_path, "13_Certification Resources and Tools", "01_Useful Websites and Forums.md"))
    create_file(os.path.join(certification_path, "13_Certification Resources and Tools", "02_Tools for Exam Preparation.md"))
    create_file(os.path.join(certification_path, "13_Certification Resources and Tools", "03_Mobile Apps for Certification Study.md"))

def create_cloud_security_structure(base_path):
    cloud_security_path = os.path.join(base_path, "Cloud Security")
    create_directory(cloud_security_path)
    create_file(os.path.join(cloud_security_path, "01_Introduction.md"))
    create_directory(os.path.join(cloud_security_path, "02_Fundamentals"))
    create_file(os.path.join(cloud_security_path, "02_Fundamentals", "01_Cloud Computing Basics.md"))
    create_file(os.path.join(cloud_security_path, "02_Fundamentals", "02_Key Concepts in Cloud Security.md"))
    create_directory(os.path.join(cloud_security_path, "03_Cloud Service Providers"))
    create_file(os.path.join(cloud_security_path, "03_Cloud Service Providers", "01_Amazon Web Services (AWS).md"))
    create_file(os.path.join(cloud_security_path, "03_Cloud Service Providers", "02_Microsoft Azure.md"))
    create_file(os.path.join(cloud_security_path, "03_Cloud Service Providers", "03_Google Cloud Platform (GCP).md"))
    create_directory(os.path.join(cloud_security_path, "04_Security Measures"))
    create_file(os.path.join(cloud_security_path, "04_Security Measures", "01_Identity and Access Management.md"))
    create_file(os.path.join(cloud_security_path, "04_Security Measures", "02_Network Security in the Cloud.md"))
    create_file(os.path.join(cloud_security_path, "04_Security Measures", "03_Data Encryption in the Cloud.md"))
    create_file(os.path.join(cloud_security_path, "04_Security Measures", "04_Compliance and Legal Considerations.md"))
    create_directory(os.path.join(cloud_security_path, "05_Cloud Security Best Practices"))
    create_file(os.path.join(cloud_security_path, "05_Cloud Security Best Practices", "01_Configuration Management.md"))
    create_file(os.path.join(cloud_security_path, "05_Cloud Security Best Practices", "02_Incident Response in the Cloud.md"))
    create_file(os.path.join(cloud_security_path, "05_Cloud Security Best Practices", "03_Monitoring and Auditing.md"))
    create_file(os.path.join(cloud_security_path, "05_Cloud Security Best Practices", "04_Secure Development in the Cloud.md"))
    create_directory(os.path.join(cloud_security_path, "06_Advanced Topics"))
    create_file(os.path.join(cloud_security_path, "06_Advanced Topics", "01_Serverless Security.md"))
    create_file(os.path.join(cloud_security_path, "06_Advanced Topics", "02_Container Security.md"))
    create_file(os.path.join(cloud_security_path, "06_Advanced Topics", "03_Automation in Cloud Security.md"))
    create_directory(os.path.join(cloud_security_path, "07_Learning Resources"))
    create_file(os.path.join(cloud_security_path, "07_Learning Resources", "01_Books.md"))
    create_file(os.path.join(cloud_security_path, "07_Learning Resources", "02_Online Courses.md"))
    create_file(os.path.join(cloud_security_path, "07_Learning Resources", "03_Certifications.md"))
    create_file(os.path.join(cloud_security_path, "07_Learning Resources", "04_Blogs and Articles.md"))

def create_ctf_structure(base_path):
    ctf_path = os.path.join(base_path, "CTF")
    create_directory(ctf_path)
    create_file(os.path.join(ctf_path, "01_Introduction.md"))
    create_directory(os.path.join(ctf_path, "02_Getting Started"))
    create_file(os.path.join(ctf_path, "02_Getting Started", "01_CTF Basics.md"))
    create_file(os.path.join(ctf_path, "02_Getting Started", "02_CTF Platforms.md"))
    create_file(os.path.join(ctf_path, "02_Getting Started", "03_Tools for CTF.md"))
    create_directory(os.path.join(ctf_path, "03_CTF Challenges"))
    create_file(os.path.join(ctf_path, "03_CTF Challenges", "01_Web Exploitation.md"))
    create_file(os.path.join(ctf_path, "03_CTF Challenges", "02_Binary Exploitation.md"))
    create_file(os.path.join(ctf_path, "03_CTF Challenges", "03_Crypto.md"))
    create_file(os.path.join(ctf_path, "03_CTF Challenges", "04_Steganography.md"))
    create_file(os.path.join(ctf_path, "03_CTF Challenges", "05_Forensics.md"))
    create_file(os.path.join(ctf_path, "03_CTF Challenges", "06_Reversing.md"))
    create_file(os.path.join(ctf_path, "03_CTF Challenges", "07_Miscellaneous.md"))
    create_directory(os.path.join(ctf_path, "04_CTF Write-ups"))
    create_file(os.path.join(ctf_path, "04_CTF Write-ups", "01_Web Exploitation.md"))
    create_file(os.path.join(ctf_path, "04_CTF Write-ups", "02_Binary Exploitation.md"))
    create_file(os.path.join(ctf_path, "04_CTF Write-ups", "03_Crypto.md"))
    create_file(os.path.join(ctf_path, "04_CTF Write-ups", "04_Steganography.md"))
    create_file(os.path.join(ctf_path, "04_CTF Write-ups", "05_Forensics.md"))
    create_file(os.path.join(ctf_path, "04_CTF Write-ups", "06_Reversing.md"))
    create_file(os.path.join(ctf_path, "04_CTF Write-ups", "07_Miscellaneous.md"))
    create_directory(os.path.join(ctf_path, "05_Tools for CTF"))
    create_file(os.path.join(ctf_path, "05_Tools for CTF", "01_Enumeration.md"))
    create_file(os.path.join(ctf_path, "05_Tools for CTF", "02_Exploitation.md"))
    create_file(os.path.join(ctf_path, "05_Tools for CTF", "03_Forensics.md"))
    create_file(os.path.join(ctf_path, "05_Tools for CTF", "04_Reversing.md"))
    create_file(os.path.join(ctf_path, "05_Tools for CTF", "05_Miscellaneous.md"))
    create_directory(os.path.join(ctf_path, "06_Learning Resources"))
    create_file(os.path.join(ctf_path, "06_Learning Resources", "01_Books.md"))
    create_file(os.path.join(ctf_path, "06_Learning Resources", "02_Online Platforms.md"))
    create_file(os.path.join(ctf_path, "06_Learning Resources", "03_Write-ups and Tutorials.md"))



def create_home_server_structure(base_path):
    home_server_path = os.path.join(base_path, "Home Server")
    create_directory(home_server_path)
    create_file(os.path.join(home_server_path, "01_Introduction.md"))
    create_directory(os.path.join(home_server_path, "02_Setting Up a Home Server"))
    create_file(os.path.join(home_server_path, "02_Setting Up a Home Server", "01_Hardware Requirements.md"))
    create_file(os.path.join(home_server_path, "02_Setting Up a Home Server", "02_Operating System Installation.md"))
    create_file(os.path.join(home_server_path, "02_Setting Up a Home Server", "03_Network Configuration.md"))
    create_directory(os.path.join(home_server_path, "03_Home Server Applications"))
    create_file(os.path.join(home_server_path, "03_Home Server Applications", "01_Media Server.md"))
    create_file(os.path.join(home_server_path, "03_Home Server Applications", "02_File Server.md"))
    create_file(os.path.join(home_server_path, "03_Home Server Applications", "03_Backup and Sync Solutions.md"))
    create_file(os.path.join(home_server_path, "03_Home Server Applications", "04_Personal Website and Blog.md"))
    create_file(os.path.join(home_server_path, "03_Home Server Applications", "05_Remote Access and VPN.md"))
    create_directory(os.path.join(home_server_path, "04_Security Considerations"))
    create_file(os.path.join(home_server_path, "04_Security Considerations", "01_Firewall Configuration.md"))
    create_file(os.path.join(home_server_path, "04_Security Considerations", "02_SSL-TLS Encryption.md"))
    create_file(os.path.join(home_server_path, "04_Security Considerations", "03_User Authentication.md"))
    create_directory(os.path.join(home_server_path, "05_Maintenance and Troubleshooting"))
    create_file(os.path.join(home_server_path, "05_Maintenance and Troubleshooting", "01_Regular Backups.md"))
    create_file(os.path.join(home_server_path, "05_Maintenance and Troubleshooting", "02_Log Monitoring.md"))
    create_file(os.path.join(home_server_path, "05_Maintenance and Troubleshooting", "03_Troubleshooting Common Issues.md"))
    create_directory(os.path.join(home_server_path, "06_Learning Resources"))
    create_file(os.path.join(home_server_path, "06_Learning Resources", "01_Books.md"))
    create_file(os.path.join(home_server_path, "06_Learning Resources", "02_Online Tutorials.md"))
    create_file(os.path.join(home_server_path, "06_Learning Resources", "03_Communities and Forums.md"))


def create_malware_structure(base_path):
    malware_path = os.path.join(base_path, "Malware")
    create_directory(malware_path)
    create_file(os.path.join(malware_path, "01_Introduction.md"))
    create_directory(os.path.join(malware_path, "02_Types of Malware"))
    create_file(os.path.join(malware_path, "02_Types of Malware", "01_Viruses.md"))
    create_file(os.path.join(malware_path, "02_Types of Malware", "02_Worms.md"))
    create_file(os.path.join(malware_path, "02_Types of Malware", "03_Trojans.md"))
    create_file(os.path.join(malware_path, "02_Types of Malware", "04_Spyware.md"))
    create_file(os.path.join(malware_path, "02_Types of Malware", "05_Ransomware.md"))
    create_file(os.path.join(malware_path, "02_Types of Malware", "06_Adware.md"))
    create_directory(os.path.join(malware_path, "03_Malware Analysis"))
    create_file(os.path.join(malware_path, "03_Malware Analysis", "01_Static Analysis.md"))
    create_file(os.path.join(malware_path, "03_Malware Analysis", "02_Dynamic Analysis.md"))
    create_file(os.path.join(malware_path, "03_Malware Analysis", "03_Code Reverse Engineering.md"))
    create_directory(os.path.join(malware_path, "04_Malware Detection and Prevention"))
    create_file(os.path.join(malware_path, "04_Malware Detection and Prevention", "01_Antivirus Software.md"))
    create_file(os.path.join(malware_path, "04_Malware Detection and Prevention", "02_Intrusion Detection Systems.md"))
    create_file(os.path.join(malware_path, "04_Malware Detection and Prevention", "03_Firewalls.md"))
    create_directory(os.path.join(malware_path, "05_Response and Mitigation"))
    create_file(os.path.join(malware_path, "05_Response and Mitigation", "01_Incident Response.md"))
    create_file(os.path.join(malware_path, "05_Response and Mitigation", "02_Malware Removal.md"))
    create_file(os.path.join(malware_path, "05_Response and Mitigation", "03_Recovery.md"))
    create_directory(os.path.join(malware_path, "06_Legal and Ethical Considerations"))
    create_file(os.path.join(malware_path, "06_Legal and Ethical Considerations", "01_Laws and Regulations.md"))
    create_file(os.path.join(malware_path, "06_Legal and Ethical Considerations", "02_Ethical Hacking.md"))
    create_directory(os.path.join(malware_path, "07_Learning Resources"))
    create_file(os.path.join(malware_path, "07_Learning Resources", "01_Books.md"))
    create_file(os.path.join(malware_path, "07_Learning Resources", "02_Online Courses.md"))
    create_file(os.path.join(malware_path, "07_Learning Resources", "03_Labs and Exercises.md"))


def create_mobile_security_structure(base_path):
    mobile_security_path = os.path.join(base_path, "Mobile Security")
    create_directory(mobile_security_path)
    create_file(os.path.join(mobile_security_path, "01_Introduction.md"))
    create_directory(os.path.join(mobile_security_path, "02_Mobile Application Security"))
    create_file(os.path.join(mobile_security_path, "02_Mobile Application Security", "01_Application Testing.md"))
    create_file(os.path.join(mobile_security_path, "02_Mobile Application Security", "02_Code Review.md"))
    create_file(os.path.join(mobile_security_path, "02_Mobile Application Security", "03_Reverse Engineering.md"))
    create_directory(os.path.join(mobile_security_path, "03_Mobile Device Security"))
    create_file(os.path.join(mobile_security_path, "03_Mobile Device Security", "01_iOS Security.md"))
    create_file(os.path.join(mobile_security_path, "03_Mobile Device Security", "02_Android Security.md"))
    create_file(os.path.join(mobile_security_path, "03_Mobile Device Security", "03_Mobile Device Management.md"))
    create_directory(os.path.join(mobile_security_path, "04_Mobile Threats"))
    create_file(os.path.join(mobile_security_path, "04_Mobile Threats", "01_Malware.md"))
    create_file(os.path.join(mobile_security_path, "04_Mobile Threats", "02_Phishing Attacks.md"))
    create_file(os.path.join(mobile_security_path, "04_Mobile Threats", "03_Social Engineering.md"))
    create_directory(os.path.join(mobile_security_path, "05_Mobile Security Best Practices"))
    create_file(os.path.join(mobile_security_path, "05_Mobile Security Best Practices", "01_Secure Coding Guidelines.md"))
    create_file(os.path.join(mobile_security_path, "05_Mobile Security Best Practices", "02_Data Encryption.md"))
    create_file(os.path.join(mobile_security_path, "05_Mobile Security Best Practices", "03_Secure Communication.md"))
    create_directory(os.path.join(mobile_security_path, "06_Learning Resources"))
    create_file(os.path.join(mobile_security_path, "06_Learning Resources", "01_Books.md"))
    create_file(os.path.join(mobile_security_path, "06_Learning Resources", "02_Online Courses.md"))
    create_file(os.path.join(mobile_security_path, "06_Learning Resources", "03_Blogs and Forums.md"))


def create_network_security_structure(base_path):
    network_security_path = os.path.join(base_path, "Network Security")
    create_directory(network_security_path)
    create_file(os.path.join(network_security_path, "01_Introduction.md"))
    create_directory(os.path.join(network_security_path, "02_Network Fundamentals"))
    create_file(os.path.join(network_security_path, "02_Network Fundamentals", "01_Network Protocols.md"))
    create_file(os.path.join(network_security_path, "02_Network Fundamentals", "02_IP Addressing.md"))
    create_file(os.path.join(network_security_path, "02_Network Fundamentals", "03_Subnetting.md"))
    create_directory(os.path.join(network_security_path, "03_Network Devices"))
    create_file(os.path.join(network_security_path, "03_Network Devices", "01_Routers.md"))
    create_file(os.path.join(network_security_path, "03_Network Devices", "02_Switches.md"))
    create_file(os.path.join(network_security_path, "03_Network Devices", "03_Firewalls.md"))
    create_directory(os.path.join(network_security_path, "04_Network Security Protocols"))
    create_file(os.path.join(network_security_path, "04_Network Security Protocols", "01_SSL-TLS.md"))
    create_file(os.path.join(network_security_path, "04_Network Security Protocols", "02_IPsec.md"))
    create_file(os.path.join(network_security_path, "04_Network Security Protocols", "03_SSL VPN.md"))
    create_directory(os.path.join(network_security_path, "05_Network Security Threats"))
    create_file(os.path.join(network_security_path, "05_Network Security Threats", "01_Malware.md"))
    create_file(os.path.join(network_security_path, "05_Network Security Threats", "02_DDoS Attacks.md"))
    create_file(os.path.join(network_security_path, "05_Network Security Threats", "03_Intrusion Detection and Prevention.md"))
    create_directory(os.path.join(network_security_path, "06_Wireless Network Security"))
    create_file(os.path.join(network_security_path, "06_Wireless Network Security", "01_Wi-Fi Security.md"))
    create_file(os.path.join(network_security_path, "06_Wireless Network Security", "02_WPA3 and Enhanced Security.md"))
    create_directory(os.path.join(network_security_path, "07_Network Security Best Practices"))
    create_file(os.path.join(network_security_path, "07_Network Security Best Practices", "01_Secure Configurations.md"))
    create_file(os.path.join(network_security_path, "07_Network Security Best Practices", "02_Auditing and Monitoring.md"))
    create_file(os.path.join(network_security_path, "07_Network Security Best Practices", "03_Incident Response.md"))
    create_directory(os.path.join(network_security_path, "08_Learning Resources"))
    create_file(os.path.join(network_security_path, "08_Learning Resources", "01_Books.md"))
    create_file(os.path.join(network_security_path, "08_Learning Resources", "02_Online Courses.md"))
    create_file(os.path.join(network_security_path, "08_Learning Resources", "03_Forums and Communities.md"))


def create_osint_structure(base_path):
    osint_path = os.path.join(base_path, "OSINT")
    create_directory(osint_path)
    create_file(os.path.join(osint_path, "01_Introduction.md"))
    create_directory(os.path.join(osint_path, "02_Operational Security"))
    create_file(os.path.join(osint_path, "02_Operational Security", "01_Social Media Security.md"))
    create_file(os.path.join(osint_path, "02_Operational Security", "02_Physical Security.md"))
    create_directory(os.path.join(osint_path, "03_Information Gathering"))
    create_file(os.path.join(osint_path, "03_Information Gathering", "01_Open Source Intelligence.md"))
    create_file(os.path.join(osint_path, "03_Information Gathering", "02_Online Presence Enumeration.md"))
    create_file(os.path.join(osint_path, "03_Information Gathering", "03_Domain Information Gathering.md"))
    create_directory(os.path.join(osint_path, "04_Social Engineering"))
    create_file(os.path.join(osint_path, "04_Social Engineering", "01_Phishing.md"))
    create_file(os.path.join(osint_path, "04_Social Engineering", "02_Impersonation.md"))
    create_directory(os.path.join(osint_path, "05_Tool Usage"))
    create_file(os.path.join(osint_path, "05_Tool Usage", "01_OSINT Tools.md"))
    create_file(os.path.join(osint_path, "05_Tool Usage", "02_Social Engineering Tools.md"))
    create_directory(os.path.join(osint_path, "06_Learning Resources"))
    create_file(os.path.join(osint_path, "06_Learning Resources", "01_Books.md"))
    create_file(os.path.join(osint_path, "06_Learning Resources", "02_Online Courses.md"))
    create_file(os.path.join(osint_path, "06_Learning Resources", "03_Blogs and Websites.md"))


def create_red_teaming_structure(base_path):
    red_team_path = os.path.join(base_path, "Red Teaming")
    create_directory(red_team_path)
    create_file(os.path.join(red_team_path, "01_Introduction.md"))
    create_directory(os.path.join(red_team_path, "02_Planning and Reconnaissance"))
    create_file(os.path.join(red_team_path, "02_Planning and Reconnaissance", "01_Organizational Mapping.md"))
    create_file(os.path.join(red_team_path, "02_Planning and Reconnaissance", "02_Social Engineering.md"))
    create_directory(os.path.join(red_team_path, "03_Weaponization"))
    create_file(os.path.join(red_team_path, "03_Weaponization", "01_Exploits and Payloads.md"))
    create_file(os.path.join(red_team_path, "03_Weaponization", "02_Phishing.md"))
    create_directory(os.path.join(red_team_path, "04_Delivery"))
    create_file(os.path.join(red_team_path, "04_Delivery", "01_Physical Drop.md"))
    create_file(os.path.join(red_team_path, "04_Delivery", "02_Remote Delivery.md"))
    create_directory(os.path.join(red_team_path, "05_Exploitation"))
    create_file(os.path.join(red_team_path, "05_Exploitation", "01_Post-Exploitation.md"))
    create_file(os.path.join(red_team_path, "05_Exploitation", "02_Privilege Escalation.md"))
    create_directory(os.path.join(red_team_path, "06_Post-Exploitation"))
    create_file(os.path.join(red_team_path, "06_Post-Exploitation", "01_Data Exfiltration.md"))
    create_file(os.path.join(red_team_path, "06_Post-Exploitation", "02_Persistence.md"))
    create_file(os.path.join(red_team_path, "06_Post-Exploitation", "03_Anti-Forensics.md"))
    create_directory(os.path.join(red_team_path, "07_Report and Debrief"))
    create_file(os.path.join(red_team_path, "07_Report and Debrief", "01_Report Writing.md"))
    create_file(os.path.join(red_team_path, "07_Report and Debrief", "02_Client Debrief.md"))
    create_directory(os.path.join(red_team_path, "08_Learning Resources"))
    create_file(os.path.join(red_team_path, "08_Learning Resources", "01_Books.md"))
    create_file(os.path.join(red_team_path, "08_Learning Resources", "02_Online Courses.md"))
    create_file(os.path.join(red_team_path, "08_Learning Resources", "03_Labs and Simulations.md"))


def create_social_engineering_structure(base_path):
    social_engineering_path = os.path.join(base_path, "Social Engineering")
    create_directory(social_engineering_path)
    create_file(os.path.join(social_engineering_path, "01_Introduction.md"))
    create_file(os.path.join(social_engineering_path, "02_Phishing.md"))
    create_file(os.path.join(social_engineering_path, "03_Impersonation.md"))
    create_file(os.path.join(social_engineering_path, "04_Quizzes and Assessments.md"))
    create_file(os.path.join(social_engineering_path, "05_Physical Social Engineering.md"))
    create_file(os.path.join(social_engineering_path, "06_Tools and Techniques.md"))
    create_file(os.path.join(social_engineering_path, "07_Case Studies.md"))
    create_file(os.path.join(social_engineering_path, "08_Prevention and Mitigation.md"))
    create_directory(os.path.join(social_engineering_path, "09_Learning Resources"))
    create_file(os.path.join(social_engineering_path, "09_Learning Resources", "01_Books.md"))
    create_file(os.path.join(social_engineering_path, "09_Learning Resources", "02_Online Courses.md"))
    create_file(os.path.join(social_engineering_path, "09_Learning Resources", "03_Blogs and Articles.md"))


def create_web_security_structure(base_path):
    web_security_path = os.path.join(base_path, "Web Security")
    create_directory(web_security_path)
    create_file(os.path.join(web_security_path, "01_Introduction.md"))
    create_file(os.path.join(web_security_path, "02_Web Application Basics.md"))
    create_file(os.path.join(web_security_path, "03_Web Application Architecture.md"))
    create_file(os.path.join(web_security_path, "04_Web Application Technologies.md"))
    create_directory(os.path.join(web_security_path, "05_Web Application Attacks"))
    create_file(os.path.join(web_security_path, "05_Web Application Attacks", "01_Injection Attacks"))
    create_file(os.path.join(web_security_path, "05_Web Application Attacks", "02_Security Misconfigurations"))
    create_directory(os.path.join(web_security_path, "06_Web Application Testing"))
    create_file(os.path.join(web_security_path, "06_Web Application Testing", "01_Static Analysis.md"))
    create_file(os.path.join(web_security_path, "06_Web Application Testing", "02_Dynamic Analysis.md"))
    create_file(os.path.join(web_security_path, "06_Web Application Testing", "03_Automated Testing.md"))
    create_directory(os.path.join(web_security_path, "07_Web Application Security Tools"))
    create_file(os.path.join(web_security_path, "07_Web Application Security Tools", "01_Burp Suite.md"))
    create_file(os.path.join(web_security_path, "07_Web Application Security Tools", "02_OWASP ZAP.md"))
    create_directory(os.path.join(web_security_path, "08_Advanced Web Security Topics"))
    create_file(os.path.join(web_security_path, "08_Advanced Web Security Topics", "01_API Security.md"))
    create_file(os.path.join(web_security_path, "08_Advanced Web Security Topics", "02_Serverless Security.md"))
    create_directory(os.path.join(web_security_path, "09_Learning Resources"))
    create_file(os.path.join(web_security_path, "09_Learning Resources", "01_Books.md"))
    create_file(os.path.join(web_security_path, "09_Learning Resources", "02_Online Courses.md"))
    create_file(os.path.join(web_security_path, "09_Learning Resources", "03_Blogs and Articles.md"))


if __name__ == "__main__":
    base_directory = "/home/wasp/test"  # Replace with your Obsidian vault path
    create_bug_bounty_structure(base_directory)
    create_certification_structure(base_directory)
    create_cloud_security_structure(base_directory)
    create_ctf_structure(base_directory)
    create_home_server_structure(base_directory)
    create_malware_structure(base_directory)
    create_mobile_security_structure(base_directory)
    create_network_security_structure(base_directory)
    create_osint_structure(base_directory)
    create_red_teaming_structure(base_directory)
    create_social_engineering_structure(base_directory)
    create_web_security_structure(base_directory)
    print("Vault created successfully.")
