import os

def create_directory(path):
    if not os.path.exists(path):
        os.makedirs(path)

def create_bug_bounty_structure(base_path):
    bug_bounty_path = os.path.join(base_path, "Bug Bounty")

    # Main Directories
    create_directory(bug_bounty_path)
    create_directory(os.path.join(bug_bounty_path, "01_Introduction"))
    create_directory(os.path.join(bug_bounty_path, "02_Getting Started"))
    create_directory(os.path.join(bug_bounty_path, "02_Getting Started", "01_Creating Bug Bounty Accounts"))
    create_directory(os.path.join(bug_bounty_path, "02_Getting Started", "02_Understanding Bug Bounty Platforms"))
    create_directory(os.path.join(bug_bounty_path, "02_Getting Started", "03_Profile Setup and Verification"))
    create_directory(os.path.join(bug_bounty_path, "03_Methodologies and Processes"))
    create_directory(os.path.join(bug_bounty_path, "03_Methodologies and Processes", "01_Reconnaissance Techniques"))
    create_directory(os.path.join(bug_bounty_path, "03_Methodologies and Processes", "01_Reconnaissance Techniques", "01_Passive and Active Recon"))
    create_directory(os.path.join(bug_bounty_path, "03_Methodologies and Processes", "01_Reconnaissance Techniques", "02_Information Gathering Tools"))
    create_directory(os.path.join(bug_bounty_path, "03_Methodologies and Processes", "02_Vulnerability Discovery"))
    create_directory(os.path.join(bug_bounty_path, "03_Methodologies and Processes", "02_Vulnerability Discovery", "01_Automated Scanning"))
    create_directory(os.path.join(bug_bounty_path, "03_Methodologies and Processes", "02_Vulnerability Discovery", "02_Manual Testing"))
    create_directory(os.path.join(bug_bounty_path, "03_Methodologies and Processes", "03_Exploitation"))
    create_directory(os.path.join(bug_bounty_path, "03_Methodologies and Processes", "03_Exploitation", "01_Techniques for Proving Impact"))
    create_directory(os.path.join(bug_bounty_path, "03_Methodologies and Processes", "03_Exploitation", "02_Exploitation Tools"))
    create_directory(os.path.join(bug_bounty_path, "03_Methodologies and Processes", "04_Post-Exploitation"))
    create_directory(os.path.join(bug_bounty_path, "03_Methodologies and Processes", "04_Post-Exploitation", "01_Data Exfiltration"))
    create_directory(os.path.join(bug_bounty_path, "03_Methodologies and Processes", "04_Post-Exploitation", "02_Pivoting"))
    create_directory(os.path.join(bug_bounty_path, "03_Methodologies and Processes", "04_Post-Exploitation", "03_Privilege Escalation"))
    create_directory(os.path.join(bug_bounty_path, "03_Methodologies and Processes", "05_Reporting and Collaboration"))
    create_directory(os.path.join(bug_bounty_path, "03_Methodologies and Processes", "05_Reporting and Collaboration", "01_Crafting Effective Reports"))
    create_directory(os.path.join(bug_bounty_path, "03_Methodologies and Processes", "05_Reporting and Collaboration", "02_Collaborating with Program Owners"))
    create_directory(os.path.join(bug_bounty_path, "04_Strategies and Tips"))
    create_directory(os.path.join(bug_bounty_path, "04_Strategies and Tips", "01_Goal-Oriented Testing"))
    create_directory(os.path.join(bug_bounty_path, "04_Strategies and Tips", "02_Target Selection"))
    create_directory(os.path.join(bug_bounty_path, "04_Strategies and Tips", "03_Time Management"))
    create_directory(os.path.join(bug_bounty_path, "04_Strategies and Tips", "04_Continuous Learning"))
    create_directory(os.path.join(bug_bounty_path, "04_Strategies and Tips", "05_Bug Bounty Etiquette"))
    create_directory(os.path.join(bug_bounty_path, "05_Tools"))
    create_directory(os.path.join(bug_bounty_path, "05_Tools", "01_Reconnaissance Tools"))
    create_directory(os.path.join(bug_bounty_path, "05_Tools", "01_Reconnaissance Tools", "01_Subdomain Enumeration"))
    create_directory(os.path.join(bug_bounty_path, "05_Tools", "01_Reconnaissance Tools", "02_WHOIS Lookup"))
    create_directory(os.path.join(bug_bounty_path, "05_Tools", "01_Reconnaissance Tools", "03_DNS Analysis"))
    create_directory(os.path.join(bug_bounty_path, "05_Tools", "02_Vulnerability Scanning Tools"))
    create_directory(os.path.join(bug_bounty_path, "05_Tools", "02_Vulnerability Scanning Tools", "01_Automated Scanners (e.g., Nikto, Nmap)"))
    create_directory(os.path.join(bug_bounty_path, "05_Tools", "02_Vulnerability Scanning Tools", "02_Manual Testing Tools (e.g., Burp Suite, OWASP ZAP)"))
    create_directory(os.path.join(bug_bounty_path, "05_Tools", "03_Exploitation Tools"))
    create_directory(os.path.join(bug_bounty_path, "05_Tools", "03_Exploitation Tools", "01_Metasploit"))
    create_directory(os.path.join(bug_bounty_path, "05_Tools", "03_Exploitation Tools", "02_ExploitDB"))
    create_directory(os.path.join(bug_bounty_path, "05_Tools", "03_Exploitation Tools", "03_Buffer Overflow Tools"))
    create_directory(os.path.join(bug_bounty_path, "05_Tools", "04_Post-Exploitation Tools"))
    create_directory(os.path.join(bug_bounty_path, "05_Tools", "04_Post-Exploitation Tools", "01_Data Exfiltration Tools"))
    create_directory(os.path.join(bug_bounty_path, "05_Tools", "04_Post-Exploitation Tools", "02_Privilege Escalation Scripts"))
    create_directory(os.path.join(bug_bounty_path, "05_Tools", "04_Post-Exploitation Tools", "03_Pivoting Utilities"))
    create_directory(os.path.join(bug_bounty_path, "05_Tools", "05_Reporting Tools"))
    create_directory(os.path.join(bug_bounty_path, "05_Tools", "05_Reporting Tools", "01_Bug Bounty Platforms"))
    create_directory(os.path.join(bug_bounty_path, "05_Tools", "05_Reporting Tools", "02_Collaborative Platforms (e.g., HackerOne, Bugcrowd)"))
    create_directory(os.path.join(bug_bounty_path, "05_Tools", "05_Reporting Tools", "03_Version Control Systems (e.g., Git)"))
    create_directory(os.path.join(bug_bounty_path, "06_Learning Resources"))
    create_directory(os.path.join(bug_bounty_path, "06_Learning Resources", "01_Books"))
    create_directory(os.path.join(bug_bounty_path, "06_Learning Resources", "01_Books", "01_Essential Bug Bounty Reading"))
    create_directory(os.path.join(bug_bounty_path, "06_Learning Resources", "01_Books", "02_Web Application Security Books"))
    create_directory(os.path.join(bug_bounty_path, "06_Learning Resources", "02_Courses"))
    create_directory(os.path.join(bug_bounty_path, "06_Learning Resources", "02_Courses", "01_Online Platforms Offering Bug Bounty Courses"))
    create_directory(os.path.join(bug_bounty_path, "06_Learning Resources", "02_Courses", "02_Certifications to Boost Bug Bounty Skills"))
    create_directory(os.path.join(bug_bounty_path, "06_Learning Resources", "03_Websites and Forums"))
    create_directory(os.path.join(bug_bounty_path, "06_Learning Resources", "03_Websites and Forums", "01_Active Bug Bounty Communities"))
    create_directory(os.path.join(bug_bounty_path, "06_Learning Resources", "03_Websites and Forums", "02_Platforms for Information Sharing"))
    create_directory(os.path.join(bug_bounty_path, "06_Learning Resources", "04_Blogs and Write-ups"))
    create_directory(os.path.join(bug_bounty_path, "06_Learning Resources", "04_Blogs and Write-ups", "01_Learning from Real-world Examples"))
    create_directory(os.path.join(bug_bounty_path, "06_Learning Resources", "04_Blogs and Write-ups", "02_Following Successful Bug Hunters"))
    create_directory(os.path.join(bug_bounty_path, "07_Challenges and Labs"))
    create_directory(os.path.join(bug_bounty_path, "07_Challenges and Labs", "01_CTF Platforms"))
    create_directory(os.path.join(bug_bounty_path, "07_Challenges and Labs", "01_CTF Platforms", "01_Practicing with Capture The Flag Challenges"))
    create_directory(os.path.join(bug_bounty_path, "07_Challenges and Labs", "01_CTF Platforms", "02_CTF Write-ups and Analysis"))
    create_directory(os.path.join(bug_bounty_path, "07_Challenges and Labs", "02_Bug Bounty Platforms with Labs"))
    create_directory(os.path.join(bug_bounty_path, "07_Challenges and Labs", "02_Bug Bounty Platforms with Labs", "01_Hands-on Practice with Simulated Environments"))
    create_directory(os.path.join(bug_bounty_path, "07_Challenges and Labs", "02_Bug Bounty Platforms with Labs", "02_Leveraging Lab Environments for Skill Development"))
    create_directory(os.path.join(bug_bounty_path, "08_Bug Bounty in Practice"))
    create_directory(os.path.join(bug_bounty_path, "08_Bug Bounty in Practice", "01_Case Studies"))
    create_directory(os.path.join(bug_bounty_path, "08_Bug Bounty in Practice", "01_Case Studies", "01_Notable Bug Bounty Success Stories"))
    create_directory(os.path.join(bug_bounty_path, "08_Bug Bounty in Practice", "01_Case Studies", "02_Lessons Learned from Public Disclosures"))
    create_directory(os.path.join(bug_bounty_path, "08_Bug Bounty in Practice", "02_Interviews with Bug Hunters"))
    create_directory(os.path.join(bug_bounty_path, "08_Bug Bounty in Practice", "02_Interviews with Bug Hunters", "01_Insights from Experienced Bug Bounty Hunters"))
    create_directory(os.path.join(bug_bounty_path, "08_Bug Bounty in Practice", "02_Interviews with Bug Hunters", "02_Tips for Aspiring Bug Hunters"))


def create_certification_structure(base_path):
    certification_path = os.path.join(base_path, "Certification")

    # Main Directories
    create_directory(certification_path)
    create_directory(os.path.join(certification_path, "01_Overview"))
    create_directory(os.path.join(certification_path, "02_Getting Started"))
    create_directory(os.path.join(certification_path, "02_Getting Started", "01_Choosing the Right Certification"))
    create_directory(os.path.join(certification_path, "02_Getting Started", "02_Prerequisites and Requirements"))
    create_directory(os.path.join(certification_path, "02_Getting Started", "03_Exam Preparation Strategies"))
    create_directory(os.path.join(certification_path, "03_Popular Certifications"))
    create_directory(os.path.join(certification_path, "03_Popular Certifications", "01_CEH (Certified Ethical Hacker)"))
    create_directory(os.path.join(certification_path, "03_Popular Certifications", "02_CISSP (Certified Information Systems Security Professional)"))
    create_directory(os.path.join(certification_path, "03_Popular Certifications", "03_CompTIA Security+"))
    create_directory(os.path.join(certification_path, "03_Popular Certifications", "04_OSCP (Offensive Security Certified Professional)"))
    create_directory(os.path.join(certification_path, "03_Popular Certifications", "05_OSWE (Offensive Security Web Expert)"))
    create_directory(os.path.join(certification_path, "03_Popular Certifications", "06_OSCE (Offensive Security Certified Expert)"))
    create_directory(os.path.join(certification_path, "04_Certification Tracks"))
    create_directory(os.path.join(certification_path, "04_Certification Tracks", "01_Ethical Hacking and Penetration Testing"))
    create_directory(os.path.join(certification_path, "04_Certification Tracks", "02_Network Security"))
    create_directory(os.path.join(certification_path, "04_Certification Tracks", "03_Cloud Security"))
    create_directory(os.path.join(certification_path, "04_Certification Tracks", "04_Web Application Security"))
    create_directory(os.path.join(certification_path, "04_Certification Tracks", "05_Incident Response and Forensics"))
    create_directory(os.path.join(certification_path, "05_Study Resources"))
    create_directory(os.path.join(certification_path, "05_Study Resources", "01_Books and Study Guides"))
    create_directory(os.path.join(certification_path, "05_Study Resources", "02_Online Courses and Training"))
    create_directory(os.path.join(certification_path, "05_Study Resources", "03_Practice Exams and Labs"))
    create_directory(os.path.join(certification_path, "05_Study Resources", "04_Study Groups and Communities"))
    create_directory(os.path.join(certification_path, "06_Exam Day Tips"))
    create_directory(os.path.join(certification_path, "06_Exam Day Tips", "01_Preparing for Exam Day"))
    create_directory(os.path.join(certification_path, "06_Exam Day Tips", "02_During the Exam"))
    create_directory(os.path.join(certification_path, "06_Exam Day Tips", "03_Post-Exam Activities"))
    create_directory(os.path.join(certification_path, "07_Maintaining and Renewing Certifications"))
    create_directory(os.path.join(certification_path, "07_Maintaining and Renewing Certifications", "01_Continuing Education Requirements"))
    create_directory(os.path.join(certification_path, "07_Maintaining and Renewing Certifications", "02_Renewal Processes"))
    create_directory(os.path.join(certification_path, "07_Maintaining and Renewing Certifications", "03_Staying Updated with Industry Changes"))
    create_directory(os.path.join(certification_path, "08_Certification Success Stories"))
    create_directory(os.path.join(certification_path, "08_Certification Success Stories", "01_Personal Experiences"))
    create_directory(os.path.join(certification_path, "08_Certification Success Stories", "02_Lessons Learned"))
    create_directory(os.path.join(certification_path, "08_Certification Success Stories", "03_Advice from Certified Professionals"))
    create_directory(os.path.join(certification_path, "09_Related Certifications"))
    create_directory(os.path.join(certification_path, "09_Related Certifications", "01_Vendor-Specific Certifications (e.g., Cisco, Microsoft)"))
    create_directory(os.path.join(certification_path, "09_Related Certifications", "02_Specialized Certifications (e.g., CISSP, CISM)"))
    create_directory(os.path.join(certification_path, "09_Related Certifications", "03_Industry-Recognized Certifications"))
    create_directory(os.path.join(certification_path, "10_Certification and Career Paths"))
    create_directory(os.path.join(certification_path, "10_Certification and Career Paths", "01_Planning Your Career Path"))
    create_directory(os.path.join(certification_path, "10_Certification and Career Paths", "02_Advancing Your Career with Certifications"))
    create_directory(os.path.join(certification_path, "11_Certifications in Demand"))
    create_directory(os.path.join(certification_path, "11_Certifications in Demand", "01_Emerging Certifications"))
    create_directory(os.path.join(certification_path, "11_Certifications in Demand", "02_Industry Trends and Predictions"))
    create_directory(os.path.join(certification_path, "12_Tips for Successful Certification Journey"))
    create_directory(os.path.join(certification_path, "12_Tips for Successful Certification Journey", "01_Time Management"))
    create_directory(os.path.join(certification_path, "12_Tips for Successful Certification Journey", "02_Balancing Work and Study"))
    create_directory(os.path.join(certification_path, "12_Tips for Successful Certification Journey", "03_Building a Strong Study Routine"))
    create_directory(os.path.join(certification_path, "12_Tips for Successful Certification Journey", "04_Dealing with Exam Anxiety"))
    create_directory(os.path.join(certification_path, "13_Certification Resources and Tools"))
    create_directory(os.path.join(certification_path, "13_Certification Resources and Tools", "01_Useful Websites and Forums"))
    create_directory(os.path.join(certification_path, "13_Certification Resources and Tools", "02_Tools for Exam Preparation"))
    create_directory(os.path.join(certification_path, "13_Certification Resources and Tools", "03_Mobile Apps for Certification Study"))

def create_cloud_security_structure(base_path):
    cloud_security_path = os.path.join(base_path, "Cloud Security")

    # Main Directories
    create_directory(cloud_security_path)
    create_directory(os.path.join(cloud_security_path, "01_Introduction"))
    create_directory(os.path.join(cloud_security_path, "02_Fundamentals"))
    create_directory(os.path.join(cloud_security_path, "02_Fundamentals", "01_Cloud Computing Basics"))
    create_directory(os.path.join(cloud_security_path, "02_Fundamentals", "02_Key Concepts in Cloud Security"))
    create_directory(os.path.join(cloud_security_path, "03_Cloud Service Providers"))
    create_directory(os.path.join(cloud_security_path, "03_Cloud Service Providers", "01_Amazon Web Services (AWS)"))
    create_directory(os.path.join(cloud_security_path, "03_Cloud Service Providers", "02_Microsoft Azure"))
    create_directory(os.path.join(cloud_security_path, "03_Cloud Service Providers", "03_Google Cloud Platform (GCP)"))
    create_directory(os.path.join(cloud_security_path, "04_Security Measures"))
    create_directory(os.path.join(cloud_security_path, "04_Security Measures", "01_Identity and Access Management"))
    create_directory(os.path.join(cloud_security_path, "04_Security Measures", "02_Network Security in the Cloud"))
    create_directory(os.path.join(cloud_security_path, "04_Security Measures", "03_Data Encryption in the Cloud"))
    create_directory(os.path.join(cloud_security_path, "04_Security Measures", "04_Compliance and Legal Considerations"))
    create_directory(os.path.join(cloud_security_path, "05_Cloud Security Best Practices"))
    create_directory(os.path.join(cloud_security_path, "05_Cloud Security Best Practices", "01_Configuration Management"))
    create_directory(os.path.join(cloud_security_path, "05_Cloud Security Best Practices", "02_Incident Response in the Cloud"))
    create_directory(os.path.join(cloud_security_path, "05_Cloud Security Best Practices", "03_Monitoring and Auditing"))
    create_directory(os.path.join(cloud_security_path, "05_Cloud Security Best Practices", "04_Secure Development in the Cloud"))
    create_directory(os.path.join(cloud_security_path, "06_Advanced Topics"))
    create_directory(os.path.join(cloud_security_path, "06_Advanced Topics", "01_Serverless Security"))
    create_directory(os.path.join(cloud_security_path, "06_Advanced Topics", "02_Container Security"))
    create_directory(os.path.join(cloud_security_path, "06_Advanced Topics", "03_Automation in Cloud Security"))
    create_directory(os.path.join(cloud_security_path, "07_Learning Resources"))
    create_directory(os.path.join(cloud_security_path, "07_Learning Resources", "01_Books"))
    create_directory(os.path.join(cloud_security_path, "07_Learning Resources", "02_Online Courses"))
    create_directory(os.path.join(cloud_security_path, "07_Learning Resources", "03_Certifications"))
    create_directory(os.path.join(cloud_security_path, "07_Learning Resources", "04_Blogs and Articles"))

def create_ctf_structure(base_path):
    ctf_path = os.path.join(base_path, "CTF")

    # Main Directories
    create_directory(ctf_path)
    create_directory(os.path.join(ctf_path, "01_Introduction"))
    create_directory(os.path.join(ctf_path, "02_Getting Started"))
    create_directory(os.path.join(ctf_path, "02_Getting Started", "01_CTF Basics"))
    create_directory(os.path.join(ctf_path, "02_Getting Started", "02_CTF Platforms"))
    create_directory(os.path.join(ctf_path, "02_Getting Started", "03_Tools for CTF"))
    create_directory(os.path.join(ctf_path, "03_CTF Challenges"))
    create_directory(os.path.join(ctf_path, "03_CTF Challenges", "01_Web Exploitation"))
    create_directory(os.path.join(ctf_path, "03_CTF Challenges", "02_Binary Exploitation"))
    create_directory(os.path.join(ctf_path, "03_CTF Challenges", "03_Crypto"))
    create_directory(os.path.join(ctf_path, "03_CTF Challenges", "04_Steganography"))
    create_directory(os.path.join(ctf_path, "03_CTF Challenges", "05_Forensics"))
    create_directory(os.path.join(ctf_path, "03_CTF Challenges", "06_Reversing"))
    create_directory(os.path.join(ctf_path, "03_CTF Challenges", "07_Miscellaneous"))
    create_directory(os.path.join(ctf_path, "04_CTF Write-ups"))
    create_directory(os.path.join(ctf_path, "04_CTF Write-ups", "01_Web Exploitation"))
    create_directory(os.path.join(ctf_path, "04_CTF Write-ups", "02_Binary Exploitation"))
    create_directory(os.path.join(ctf_path, "04_CTF Write-ups", "03_Crypto"))
    create_directory(os.path.join(ctf_path, "04_CTF Write-ups", "04_Steganography"))
    create_directory(os.path.join(ctf_path, "04_CTF Write-ups", "05_Forensics"))
    create_directory(os.path.join(ctf_path, "04_CTF Write-ups", "06_Reversing"))
    create_directory(os.path.join(ctf_path, "04_CTF Write-ups", "07_Miscellaneous"))
    create_directory(os.path.join(ctf_path, "05_Tools for CTF"))
    create_directory(os.path.join(ctf_path, "05_Tools for CTF", "01_Enumeration"))
    create_directory(os.path.join(ctf_path, "05_Tools for CTF", "02_Exploitation"))
    create_directory(os.path.join(ctf_path, "05_Tools for CTF", "03_Forensics"))
    create_directory(os.path.join(ctf_path, "05_Tools for CTF", "04_Reversing"))
    create_directory(os.path.join(ctf_path, "05_Tools for CTF", "05_Miscellaneous"))
    create_directory(os.path.join(ctf_path, "06_Learning Resources"))
    create_directory(os.path.join(ctf_path, "06_Learning Resources", "01_Books"))
    create_directory(os.path.join(ctf_path, "06_Learning Resources", "02_Online Platforms"))
    create_directory(os.path.join(ctf_path, "06_Learning Resources", "03_Write-ups and Tutorials"))



def create_home_server_structure(base_path):
    home_server_path = os.path.join(base_path, "Home Server")

    # Main Directories
    create_directory(home_server_path)
    create_directory(os.path.join(home_server_path, "01_Introduction"))
    create_directory(os.path.join(home_server_path, "02_Setting Up a Home Server"))
    create_directory(os.path.join(home_server_path, "02_Setting Up a Home Server", "01_Hardware Requirements"))
    create_directory(os.path.join(home_server_path, "02_Setting Up a Home Server", "02_Operating System Installation"))
    create_directory(os.path.join(home_server_path, "02_Setting Up a Home Server", "03_Network Configuration"))
    create_directory(os.path.join(home_server_path, "03_Home Server Applications"))
    create_directory(os.path.join(home_server_path, "03_Home Server Applications", "01_Media Server"))
    create_directory(os.path.join(home_server_path, "03_Home Server Applications", "02_File Server"))
    create_directory(os.path.join(home_server_path, "03_Home Server Applications", "03_Backup and Sync Solutions"))
    create_directory(os.path.join(home_server_path, "03_Home Server Applications", "04_Personal Website and Blog"))
    create_directory(os.path.join(home_server_path, "03_Home Server Applications", "05_Remote Access and VPN"))
    create_directory(os.path.join(home_server_path, "04_Security Considerations"))
    create_directory(os.path.join(home_server_path, "04_Security Considerations", "01_Firewall Configuration"))
    create_directory(os.path.join(home_server_path, "04_Security Considerations", "02_SSL/TLS Encryption"))
    create_directory(os.path.join(home_server_path, "04_Security Considerations", "03_User Authentication"))
    create_directory(os.path.join(home_server_path, "05_Maintenance and Troubleshooting"))
    create_directory(os.path.join(home_server_path, "05_Maintenance and Troubleshooting", "01_Regular Backups"))
    create_directory(os.path.join(home_server_path, "05_Maintenance and Troubleshooting", "02_Log Monitoring"))
    create_directory(os.path.join(home_server_path, "05_Maintenance and Troubleshooting", "03_Troubleshooting Common Issues"))
    create_directory(os.path.join(home_server_path, "06_Learning Resources"))
    create_directory(os.path.join(home_server_path, "06_Learning Resources", "01_Books"))
    create_directory(os.path.join(home_server_path, "06_Learning Resources", "02_Online Tutorials"))
    create_directory(os.path.join(home_server_path, "06_Learning Resources", "03_Communities and Forums"))


def create_malware_structure(base_path):
    malware_path = os.path.join(base_path, "Malware")

    # Main Directories
    create_directory(malware_path)
    create_directory(os.path.join(malware_path, "01_Introduction"))
    create_directory(os.path.join(malware_path, "02_Types of Malware"))
    create_directory(os.path.join(malware_path, "02_Types of Malware", "01_Viruses"))
    create_directory(os.path.join(malware_path, "02_Types of Malware", "02_Worms"))
    create_directory(os.path.join(malware_path, "02_Types of Malware", "03_Trojans"))
    create_directory(os.path.join(malware_path, "02_Types of Malware", "04_Spyware"))
    create_directory(os.path.join(malware_path, "02_Types of Malware", "05_Ransomware"))
    create_directory(os.path.join(malware_path, "02_Types of Malware", "06_Adware"))
    create_directory(os.path.join(malware_path, "03_Malware Analysis"))
    create_directory(os.path.join(malware_path, "03_Malware Analysis", "01_Static Analysis"))
    create_directory(os.path.join(malware_path, "03_Malware Analysis", "02_Dynamic Analysis"))
    create_directory(os.path.join(malware_path, "03_Malware Analysis", "03_Code Reverse Engineering"))
    create_directory(os.path.join(malware_path, "04_Malware Detection and Prevention"))
    create_directory(os.path.join(malware_path, "04_Malware Detection and Prevention", "01_Antivirus Software"))
    create_directory(os.path.join(malware_path, "04_Malware Detection and Prevention", "02_Intrusion Detection Systems"))
    create_directory(os.path.join(malware_path, "04_Malware Detection and Prevention", "03_Firewalls"))
    create_directory(os.path.join(malware_path, "05_Response and Mitigation"))
    create_directory(os.path.join(malware_path, "05_Response and Mitigation", "01_Incident Response"))
    create_directory(os.path.join(malware_path, "05_Response and Mitigation", "02_Malware Removal"))
    create_directory(os.path.join(malware_path, "05_Response and Mitigation", "03_Recovery"))
    create_directory(os.path.join(malware_path, "06_Legal and Ethical Considerations"))
    create_directory(os.path.join(malware_path, "06_Legal and Ethical Considerations", "01_Laws and Regulations"))
    create_directory(os.path.join(malware_path, "06_Legal and Ethical Considerations", "02_Ethical Hacking"))
    create_directory(os.path.join(malware_path, "07_Learning Resources"))
    create_directory(os.path.join(malware_path, "07_Learning Resources", "01_Books"))
    create_directory(os.path.join(malware_path, "07_Learning Resources", "02_Online Courses"))
    create_directory(os.path.join(malware_path, "07_Learning Resources", "03_Labs and Exercises"))


def create_mobile_security_structure(base_path):
    mobile_security_path = os.path.join(base_path, "Mobile Security")

    # Main Directories
    create_directory(mobile_security_path)
    create_directory(os.path.join(mobile_security_path, "01_Introduction"))
    create_directory(os.path.join(mobile_security_path, "02_Mobile Application Security"))
    create_directory(os.path.join(mobile_security_path, "02_Mobile Application Security", "01_Application Testing"))
    create_directory(os.path.join(mobile_security_path, "02_Mobile Application Security", "02_Code Review"))
    create_directory(os.path.join(mobile_security_path, "02_Mobile Application Security", "03_Reverse Engineering"))
    create_directory(os.path.join(mobile_security_path, "03_Mobile Device Security"))
    create_directory(os.path.join(mobile_security_path, "03_Mobile Device Security", "01_iOS Security"))
    create_directory(os.path.join(mobile_security_path, "03_Mobile Device Security", "02_Android Security"))
    create_directory(os.path.join(mobile_security_path, "03_Mobile Device Security", "03_Mobile Device Management"))
    create_directory(os.path.join(mobile_security_path, "04_Mobile Threats"))
    create_directory(os.path.join(mobile_security_path, "04_Mobile Threats", "01_Malware"))
    create_directory(os.path.join(mobile_security_path, "04_Mobile Threats", "02_Phishing Attacks"))
    create_directory(os.path.join(mobile_security_path, "04_Mobile Threats", "03_Social Engineering"))
    create_directory(os.path.join(mobile_security_path, "05_Mobile Security Best Practices"))
    create_directory(os.path.join(mobile_security_path, "05_Mobile Security Best Practices", "01_Secure Coding Guidelines"))
    create_directory(os.path.join(mobile_security_path, "05_Mobile Security Best Practices", "02_Data Encryption"))
    create_directory(os.path.join(mobile_security_path, "05_Mobile Security Best Practices", "03_Secure Communication"))
    create_directory(os.path.join(mobile_security_path, "06_Learning Resources"))
    create_directory(os.path.join(mobile_security_path, "06_Learning Resources", "01_Books"))
    create_directory(os.path.join(mobile_security_path, "06_Learning Resources", "02_Online Courses"))
    create_directory(os.path.join(mobile_security_path, "06_Learning Resources", "03_Blogs and Forums"))


def create_network_security_structure(base_path):
    network_security_path = os.path.join(base_path, "Network Security")

    # Main Directories
    create_directory(network_security_path)
    create_directory(os.path.join(network_security_path, "01_Introduction"))
    create_directory(os.path.join(network_security_path, "02_Network Fundamentals"))
    create_directory(os.path.join(network_security_path, "02_Network Fundamentals", "01_Network Protocols"))
    create_directory(os.path.join(network_security_path, "02_Network Fundamentals", "02_IP Addressing"))
    create_directory(os.path.join(network_security_path, "02_Network Fundamentals", "03_Subnetting"))
    create_directory(os.path.join(network_security_path, "03_Network Devices"))
    create_directory(os.path.join(network_security_path, "03_Network Devices", "01_Routers"))
    create_directory(os.path.join(network_security_path, "03_Network Devices", "02_Switches"))
    create_directory(os.path.join(network_security_path, "03_Network Devices", "03_Firewalls"))
    create_directory(os.path.join(network_security_path, "04_Network Security Protocols"))
    create_directory(os.path.join(network_security_path, "04_Network Security Protocols", "01_SSL/TLS"))
    create_directory(os.path.join(network_security_path, "04_Network Security Protocols", "02_IPsec"))
    create_directory(os.path.join(network_security_path, "04_Network Security Protocols", "03_SSL VPN"))
    create_directory(os.path.join(network_security_path, "05_Network Security Threats"))
    create_directory(os.path.join(network_security_path, "05_Network Security Threats", "01_Malware"))
    create_directory(os.path.join(network_security_path, "05_Network Security Threats", "02_DDoS Attacks"))
    create_directory(os.path.join(network_security_path, "05_Network Security Threats", "03_Intrusion Detection and Prevention"))
    create_directory(os.path.join(network_security_path, "06_Wireless Network Security"))
    create_directory(os.path.join(network_security_path, "06_Wireless Network Security", "01_Wi-Fi Security"))
    create_directory(os.path.join(network_security_path, "06_Wireless Network Security", "02_WPA3 and Enhanced Security"))
    create_directory(os.path.join(network_security_path, "07_Network Security Best Practices"))
    create_directory(os.path.join(network_security_path, "07_Network Security Best Practices", "01_Secure Configurations"))
    create_directory(os.path.join(network_security_path, "07_Network Security Best Practices", "02_Auditing and Monitoring"))
    create_directory(os.path.join(network_security_path, "07_Network Security Best Practices", "03_Incident Response"))
    create_directory(os.path.join(network_security_path, "08_Learning Resources"))
    create_directory(os.path.join(network_security_path, "08_Learning Resources", "01_Books"))
    create_directory(os.path.join(network_security_path, "08_Learning Resources", "02_Online Courses"))
    create_directory(os.path.join(network_security_path, "08_Learning Resources", "03_Forums and Communities"))


def create_osint_structure(base_path):
    osint_path = os.path.join(base_path, "OSINT")

    # Main Directories
    create_directory(osint_path)
    create_directory(os.path.join(osint_path, "01_Introduction"))
    create_directory(os.path.join(osint_path, "02_Operational Security"))
    create_directory(os.path.join(osint_path, "02_Operational Security", "01_Social Media Security"))
    create_directory(os.path.join(osint_path, "02_Operational Security", "02_Physical Security"))
    create_directory(os.path.join(osint_path, "03_Information Gathering"))
    create_directory(os.path.join(osint_path, "03_Information Gathering", "01_Open Source Intelligence"))
    create_directory(os.path.join(osint_path, "03_Information Gathering", "02_Online Presence Enumeration"))
    create_directory(os.path.join(osint_path, "03_Information Gathering", "03_Domain Information Gathering"))
    create_directory(os.path.join(osint_path, "04_Social Engineering"))
    create_directory(os.path.join(osint_path, "04_Social Engineering", "01_Phishing"))
    create_directory(os.path.join(osint_path, "04_Social Engineering", "02_Impersonation"))
    create_directory(os.path.join(osint_path, "05_Tool Usage"))
    create_directory(os.path.join(osint_path, "05_Tool Usage", "01_OSINT Tools"))
    create_directory(os.path.join(osint_path, "05_Tool Usage", "02_Social Engineering Tools"))
    create_directory(os.path.join(osint_path, "06_Learning Resources"))
    create_directory(os.path.join(osint_path, "06_Learning Resources", "01_Books"))
    create_directory(os.path.join(osint_path, "06_Learning Resources", "02_Online Courses"))
    create_directory(os.path.join(osint_path, "06_Learning Resources", "03_Blogs and Websites"))


def create_red_teaming_structure(base_path):
    red_team_path = os.path.join(base_path, "Red Teaming")

    # Main Directories
    create_directory(red_team_path)
    create_directory(os.path.join(red_team_path, "01_Introduction"))
    create_directory(os.path.join(red_team_path, "02_Planning and Reconnaissance"))
    create_directory(os.path.join(red_team_path, "02_Planning and Reconnaissance", "01_Organizational Mapping"))
    create_directory(os.path.join(red_team_path, "02_Planning and Reconnaissance", "02_Social Engineering"))
    create_directory(os.path.join(red_team_path, "03_Weaponization"))
    create_directory(os.path.join(red_team_path, "03_Weaponization", "01_Exploits and Payloads"))
    create_directory(os.path.join(red_team_path, "03_Weaponization", "02_Phishing"))
    create_directory(os.path.join(red_team_path, "04_Delivery"))
    create_directory(os.path.join(red_team_path, "04_Delivery", "01_Physical Drop"))
    create_directory(os.path.join(red_team_path, "04_Delivery", "02_Remote Delivery"))
    create_directory(os.path.join(red_team_path, "05_Exploitation"))
    create_directory(os.path.join(red_team_path, "05_Exploitation", "01_Post-Exploitation"))
    create_directory(os.path.join(red_team_path, "05_Exploitation", "02_Privilege Escalation"))
    create_directory(os.path.join(red_team_path, "06_Post-Exploitation"))
    create_directory(os.path.join(red_team_path, "06_Post-Exploitation", "01_Data Exfiltration"))
    create_directory(os.path.join(red_team_path, "06_Post-Exploitation", "02_Persistence"))
    create_directory(os.path.join(red_team_path, "06_Post-Exploitation", "03_Anti-Forensics"))
    create_directory(os.path.join(red_team_path, "07_Report and Debrief"))
    create_directory(os.path.join(red_team_path, "07_Report and Debrief", "01_Report Writing"))
    create_directory(os.path.join(red_team_path, "07_Report and Debrief", "02_Client Debrief"))
    create_directory(os.path.join(red_team_path, "08_Learning Resources"))
    create_directory(os.path.join(red_team_path, "08_Learning Resources", "01_Books"))
    create_directory(os.path.join(red_team_path, "08_Learning Resources", "02_Online Courses"))
    create_directory(os.path.join(red_team_path, "08_Learning Resources", "03_Labs and Simulations"))


def create_social_engineering_structure(base_path):
    social_engineering_path = os.path.join(base_path, "Social Engineering")

    # Main Directories
    create_directory(social_engineering_path)
    create_directory(os.path.join(social_engineering_path, "01_Introduction"))
    create_directory(os.path.join(social_engineering_path, "02_Phishing"))
    create_directory(os.path.join(social_engineering_path, "03_Impersonation"))
    create_directory(os.path.join(social_engineering_path, "04_Quizzes and Assessments"))
    create_directory(os.path.join(social_engineering_path, "05_Physical Social Engineering"))
    create_directory(os.path.join(social_engineering_path, "06_Tools and Techniques"))
    create_directory(os.path.join(social_engineering_path, "07_Case Studies"))
    create_directory(os.path.join(social_engineering_path, "08_Prevention and Mitigation"))
    create_directory(os.path.join(social_engineering_path, "09_Learning Resources"))
    create_directory(os.path.join(social_engineering_path, "09_Learning Resources", "01_Books"))
    create_directory(os.path.join(social_engineering_path, "09_Learning Resources", "02_Online Courses"))
    create_directory(os.path.join(social_engineering_path, "09_Learning Resources", "03_Blogs and Articles"))


def create_web_security_structure(base_path):
    web_security_path = os.path.join(base_path, "Web Security")

    # Main Directories
    create_directory(web_security_path)
    create_directory(os.path.join(web_security_path, "01_Introduction"))
    create_directory(os.path.join(web_security_path, "02_Web Application Basics"))
    create_directory(os.path.join(web_security_path, "03_Web Application Architecture"))
    create_directory(os.path.join(web_security_path, "04_Web Application Technologies"))
    create_directory(os.path.join(web_security_path, "05_Web Application Attacks"))
    create_directory(os.path.join(web_security_path, "05_Web Application Attacks", "01_Injection Attacks"))
    create_directory(os.path.join(web_security_path, "05_Web Application Attacks", "02_Cross-Site Scripting (XSS)"))
    create_directory(os.path.join(web_security_path, "05_Web Application Attacks", "03_Cross-Site Request Forgery (CSRF)"))
    create_directory(os.path.join(web_security_path, "05_Web Application Attacks", "04_Security Misconfigurations"))
    create_directory(os.path.join(web_security_path, "06_Web Application Testing"))
    create_directory(os.path.join(web_security_path, "06_Web Application Testing", "01_Static Analysis"))
    create_directory(os.path.join(web_security_path, "06_Web Application Testing", "02_Dynamic Analysis"))
    create_directory(os.path.join(web_security_path, "06_Web Application Testing", "03_Automated Testing"))
    create_directory(os.path.join(web_security_path, "07_Web Application Security Tools"))
    create_directory(os.path.join(web_security_path, "07_Web Application Security Tools", "01_Burp Suite"))
    create_directory(os.path.join(web_security_path, "07_Web Application Security Tools", "02_OWASP ZAP"))
    create_directory(os.path.join(web_security_path, "08_Advanced Web Security Topics"))
    create_directory(os.path.join(web_security_path, "08_Advanced Web Security Topics", "01_API Security"))
    create_directory(os.path.join(web_security_path, "08_Advanced Web Security Topics", "02_Serverless Security"))
    create_directory(os.path.join(web_security_path, "09_Learning Resources"))
    create_directory(os.path.join(web_security_path, "09_Learning Resources", "01_Books"))
    create_directory(os.path.join(web_security_path, "09_Learning Resources", "02_Online Courses"))
    create_directory(os.path.join(web_security_path, "09_Learning Resources", "03_Blogs and Articles"))

if __name__ == "__main__":
    base_directory = "/home/wasp/test"  # Replace with your Obsidian vault path
    create_bug_bounty_structure(base_directory)
    create_certification_structure(base_directory)
    create_cloud_security_structure(base_directory)
    create_ctf_structure(base_directory)
    create_home_server_structure(base_directory)
    create_malware_structure(base_directory)
    create_mobile_security_structure(base_directory)
    create_network_security_structure(base_directory)
    create_osint_structure(base_directory)
    create_red_teaming_structure(base_directory)
    create_social_engineering_structure(base_directory)
    create_web_security_structure(base_directory)
    print("Vault created successfully.")
